# Generated by Django 4.1.2 on 2022-10-19 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import vehicles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.CharField(default=vehicles.models.uuid_str, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(default=vehicles.models.uuid_str, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('license_plate', models.CharField(max_length=80, unique=True)),
                ('battery_level', models.FloatField()),
                ('in_use', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleShift',
            fields=[
                ('id', models.CharField(default=vehicles.models.uuid_str, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('swap_completed', models.BooleanField(default=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_shift', to='vehicles.shift')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_shift', to='vehicles.vehicle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vehicleshift',
            constraint=models.UniqueConstraint(fields=('vehicle', 'shift'), name='unique_vehicle_shift'),
        ),
    ]
